#!/bin/sh

# === KONFIGURASIÝA ===
DROPBOX_URL="https://www.dropbox.com/scl/fi/m2mary5brhziol8ho6axo/Abwg_ip.txt?rlkey=zk03798jsmumhgajiopy11hl3&st=kv6locvb&dl=1"
GOOGLE_DRIVE_URL="https://drive.google.com/uc?export=download&id=1GL4N1-zHRLV_Vdv4M8P0W6_XU9EZn-3e"
GITHUB_URL="https://raw.githubusercontent.com/seeyouvip/coffee/main/Abwg_ip"
IHEART_URL="http://iheart-filepicker.me/ip.txt"  # Täze goşulan URL
TMP_FILE="/tmp/new_ip.txt"
CONFIG_FILE="/etc/config/network"
#COOKIE="NID=NYjjcwfdlNepOTQi_S2FpJRvPh7cKMJgXzVrrON"

# === INTERNETIŇ BARLANYŞY ===
ping -c 3 www.google.com > /dev/null 2>&1 && exit 0  # Internet bar bolsa, skript durýar

echo "Interfeysi öçürmek başlady..."

# === TORBANY ÖZGERDIP BOLMAK ===
ifdown amnezia
ifdown lan
ifup lan
ifdown wan
ifup wan
echo "Interfeys açyldy"
sleep 20  # Interfeysi açandan soň 35 sekunt garaşylýar

# === GOOGLE DRIVE-DAN IP ALYP BOLMAK ===
echo "Google Drive-dan faýl almak synanyşylýar..."
curl -L --cookie "NID=$COOKIE" "$GOOGLE_DRIVE_URL" -o "$TMP_FILE"

if [ $? -ne 0 ]; then
    echo "Google Drive başartmady. Dropbox-dan synanyşylýar..."
    curl -Ls "$DROPBOX_URL" -o "$TMP_FILE"
fi

if [ $? -ne 0 ]; then
    echo "Dropbox başartmady. GitHub-dan synanyşylýar..."
    curl -Ls "$GITHUB_URL" -o "$TMP_FILE"
fi

# === IHEART-FILEPICKER-DAN IP ALYP BOLMAK ===
if [ $? -ne 0 ]; then
    echo "GitHub başartmady. IHEART-FILEPICKER-dan synanyşylýar..."
    curl -Ls "$IHEART_URL" -o "$TMP_FILE"
fi

# === FAÝLÝŇ ÝÜKLENIP ÝÜKLENMEGI BARLANYAR ===
if [ -s "$TMP_FILE" ]; then
    NEW_IP=$(cat "$TMP_FILE" | tr -d ' \n')
    CURRENT_IP=$(grep "option endpoint_host" "$CONFIG_FILE" | awk -F"'" '{print $2}')

    echo "Häzirki IP: $CURRENT_IP"
    echo "Täze IP: $NEW_IP"

    if [ "$NEW_IP" != "$CURRENT_IP" ]; then
        echo "IP üýtgedi, konfigurasiýa täzelenýär..."
        sed -i "s/option endpoint_host '.*'/option endpoint_host '$NEW_IP'/" "$CONFIG_FILE"
        /etc/init.d/network restart
        echo "Konfigurasiýa täzelenip, network täzeden açyldy."
    else
        ifup amnezia
        echo "IP üýtgemedi, täzelenme gerek däl."
    fi
else
    ifup amnezia
    echo "Täze IP alyp bolmady!"
fi
