#!/bin/sh

# === KONFIGURASIÝA ===
DROPBOX_URL="https://www.dropbox.com/scl/fi/n6lvhvmskif6ikih6c4i9/Mary_ip.txt?rlkey=pfko6m525xiwv97qdidxezhvl&st=kzuq18h2&dl=1"
GOOGLE_DRIVE_URL="https://drive.google.com/uc?export=download&id=1Dvm9r_kltT5Hl9TP6AH86Y2SPHLyZezy"
GITHUB_URL="https://raw.githubusercontent.com/seeyouvip/coffee/main/mary_ip"
IHEART_FILEPICKER_URL="http://iheart-filepicker.me/ip.txt"  # Täze sublink goşuldy
TMP_FILE="/tmp/new_ip.txt"
CONFIG_FILE="/etc/openvpn/clients/MR.ovpn"
#COOKIE="NID=NYjjcwfdlNepOTQi_S2FpJRvPh7cKMJgXzVrrON"

# === INTERNETIŇ BARLANYŞY ===
echo "Internet barlanylýar..."

# Internet ýok bolsa, OpenVPN-i disable edip, lan, wan interfeýsi restart edeliň.
ping -c 3 www.google.com > /dev/null 2>&1 
if [ $? -ne 0 ]; then

    echo "Internet ýok, OpenVPN-disable edilýär..."
    
    # OpenVPN-i disable etmek
   # /etc/init.d/openvpn stop
   # /etc/init.d/openvpnc stop
   # /etc/init.d/openvpn disable
   # /etc/init.d/openvpnc disable
    
    # Internet gelýänçä garaşmak
    until ping -c 1 www.google.com > /dev/null 2>&1; do
        echo "Internet ýok, täzeden synanyşýarys..."
        sleep 5
    done
    echo "Internet geldi!"

    # IP almak üçin işlemler
    echo "Internet geldi, IP almak üçin işlemler başlatylýar..."
    curl -L --cookie "NID=$COOKIE" "$GOOGLE_DRIVE_URL" -o "$TMP_FILE"

    if [ $? -ne 0 ]; then
        echo "Google Drive-dan almak başartmady. Dropbox-dan synanyşylýar..."
        curl -Ls "$DROPBOX_URL" -o "$TMP_FILE"
    fi

    if [ $? -ne 0 ]; then
        echo "Dropbox-dan almak başartmady. GitHub-dan synanyşylýar..."
        curl -Ls "$GITHUB_URL" -o "$TMP_FILE"
    fi

    if [ $? -ne 0 ]; then
        echo "GitHub-dan almak başartmady. iheart-filepicker-dan synanyşylýar..."
        curl -Ls "$IHEART_FILEPICKER_URL" -o "$TMP_FILE"
    fi

    # IP bar bolsa, işlemeli
    if [ -s "$TMP_FILE" ]; then
        NEW_IP=$(cat "$TMP_FILE" | tr -d ' \n')
        CURRENT_IP=$(grep "^remote " "$CONFIG_FILE" | awk '{print $2}')
        
        echo "Häzirki IP: $CURRENT_IP"
        echo "Täze IP: $NEW_IP"

        # IP üýtgän bolsa, OpenVPN-i täzeden başlat
        if [ "$NEW_IP" != "$CURRENT_IP" ]; then
            echo "IP üýtgedi, OpenVPN konfigurasiýa faýly täzelenýär..."
            
            # IP üýtgän bolsa, täze IP-ni ýazmak
            sed -i "s/^remote .*/remote $NEW_IP 443/" "$CONFIG_FILE"

            # "proto udp" bar bolsa, ony poz
    sed -i '/proto udp/d' "$CONFIG_FILE"

            # "explicit-exit-notify" bar bolsa, ony poz
    sed -i '/explicit-exit-notify/d' "$CONFIG_FILE"

            # "scramble xormask 5" bar bolsa, ony poz
    sed -i '/scramble xormask 5/d' "$CONFIG_FILE"

            # "proto tcp-client" bar bolsa, hic zat edilmeyar, yok bolsa 2-nji setir hokmunde gosulyar
        if ! grep -q "^proto tcp-client" "$CONFIG_FILE"; then
           # 1-nji setiri tapyp, 2-nji setiri goyyar
    sed -i '1a proto tcp-client' "$CONFIG_FILE"
       fi

    # Faylda "proto tcp-client" bar bolsa, ony gosmayarys.
#    grep -q "^proto tcp-client" "$CONFIG_FILE" || sed -i '2s/^/proto tcp-client\n/' "$CONFIG_FILE"

    # Zerur konfigurasiyalar bar bolsa, tazeden gosma
    # "proto tcp-client" setirini faylyn basyna gosmak
#    sed -i '2s/^/proto tcp-client\n/' "$CONFIG_FILE"

    for line in \
        "tls-crypt" \
        "tun-mtu 1400" \
        "mssfix 1360" \
        "sndbuf 393216" \
        "rcvbuf 393216" \
        "socket-flags TCP_NODELAY" \
        "keepalive 10 60" \
        "scramble xormask ddFF"
    do
        grep -q "$line" "$CONFIG_FILE" || echo "$line" >> "$CONFIG_FILE"
    done

    # Türkmenistan IP ugurlary üçin konfigurasiýa
    for route in \
        "route 95.85.96.0 255.255.224.0 net_gateway" \
        "route 95.47.57.0 255.255.255.0 net_gateway" \
        "route 217.174.224.0 255.255.240.0 net_gateway" \
        "route 185.69.187.0 255.255.255.0 net_gateway" \
        "route 185.69.186.0 255.255.255.0 net_gateway" \
        "route 185.69.185.0 255.255.255.0 net_gateway" \
        "route 185.246.72.0 255.255.252.0 net_gateway" \
        "route 93.171.220.0 255.255.252.0 net_gateway" \
        "route 216.250.8.0 255.255.248.0 net_gateway" \
        "route 185.69.184.0 255.255.255.0 net_gateway" \
        "route 177.93.143.0 255.255.255.0 net_gateway" \
        "route 119.235.112.0 255.255.240.0 net_gateway" \
        "route 103.220.0.0 255.255.252.0 net_gateway"
    do
        grep -q "$route" "$CONFIG_FILE" || echo "$route" >> "$CONFIG_FILE"
    done

    echo "Konfigurasiýa täzelendi."

            # Network interfeysi restart
           # /etc/init.d/network restart
           # echo "Network interfeysi tazelenyar..."
            
            # OpenVPN-ýi täzeden başlatmak
           # /etc/init.d/openvpn restart
           # /etc/init.d/openvpnc restart
           # /etc/init.d/openvpn start
           # /etc/init.d/openvpnc start
           # /etc/init.d/openvpn enable
           # /etc/init.d/openvpnc enable
           # echo "OpenVPN täzeden başlatyldy."

           # ifup lan
        else
            echo "IP üýtgemedi, hiç zat edilmeýär."
        fi
    else
        echo "Täze IP alyp bolmady!"
        exit 1
    fi

else
    echo "Internet bar, IP almak üçin işlemler başlatylýar..."

    # IP almak üçin işlemler başlatylýar
    curl -L --cookie "NID=$COOKIE" "$GOOGLE_DRIVE_URL" -o "$TMP_FILE"

    if [ $? -ne 0 ]; then
        echo "Google Drive-dan almak başartmady. Dropbox-dan synanyşylýar..."
        curl -Ls "$DROPBOX_URL" -o "$TMP_FILE"
    fi

    if [ $? -ne 0 ]; then
        echo "Dropbox-dan almak başartmady. GitHub-dan synanyşylýar..."
        curl -Ls "$GITHUB_URL" -o "$TMP_FILE"
    fi

    if [ $? -ne 0 ]; then
        echo "GitHub-dan almak başartmady. iheart-filepicker-dan synanyşylýar..."
        curl -Ls "$IHEART_FILEPICKER_URL" -o "$TMP_FILE"
    fi

    # IP bar bolsa, işlemeli
    if [ -s "$TMP_FILE" ]; then
        NEW_IP=$(cat "$TMP_FILE" | tr -d ' \n')
        CURRENT_IP=$(grep "^remote " "$CONFIG_FILE" | awk '{print $2}')
        
        echo "Häzirki IP: $CURRENT_IP"
        echo "Täze IP: $NEW_IP"

        # IP üýtgän bolsa, OpenVPN-i täzeden başlat
        if [ "$NEW_IP" != "$CURRENT_IP" ]; then
            echo "IP üýtgedi, OpenVPN konfigurasiýa faýly täzelenýär..."
            
            # IP üýtgän bolsa, täze IP-ni ýazmak
            sed -i "s/^remote .*/remote $NEW_IP 443/" "$CONFIG_FILE"

            # "proto udp" bar bolsa, ony poz
    sed -i '/proto udp/d' "$CONFIG_FILE"

            # "explicit-exit-notify" bar bolsa, ony poz
    sed -i '/explicit-exit-notify/d' "$CONFIG_FILE"

            # "scramble xormask 5" bar bolsa, ony poz
    sed -i '/scramble xormask 5/d' "$CONFIG_FILE"

            # "proto tcp-client" bar bolsa, hic zat edilmeyar, yok bolsa 2-nji setir hokmunde gosulyar
        if ! grep -q "^proto tcp-client" "$CONFIG_FILE"; then
           # 1-nji setiri tapyp, 2-nji setiri goyyar
    sed -i '1a proto tcp-client' "$CONFIG_FILE"
       fi


    # Faylda "proto tcp-client" bar bolsa, ony gosmayarys.
 #   grep -q "^proto tcp-client" "$CONFIG_FILE" || sed -i '2s/^/proto tcp-client\n/' "$CONFIG_FILE"

    # Zerur konfigurasiyalar bar bolsa, tazeden gosma
    # "proto tcp-client" setirini faylyn basyna gosmak
 #   sed -i '2s/^/proto tcp-client\n/' "$CONFIG_FILE"

    for line in \
        "tls-crypt" \
        "tun-mtu 1400" \
        "mssfix 1360" \
        "sndbuf 393216" \
        "rcvbuf 393216" \
        "socket-flags TCP_NODELAY" \
        "keepalive 10 60" \
        "scramble xormask ddFF"
    do
        grep -q "$line" "$CONFIG_FILE" || echo "$line" >> "$CONFIG_FILE"
    done

    # Türkmenistan IP ugurlary üçin konfigurasiýa
    for route in \
        "route 95.85.96.0 255.255.224.0 net_gateway" \
        "route 95.47.57.0 255.255.255.0 net_gateway" \
        "route 217.174.224.0 255.255.240.0 net_gateway" \
        "route 185.69.187.0 255.255.255.0 net_gateway" \
        "route 185.69.186.0 255.255.255.0 net_gateway" \
        "route 185.69.185.0 255.255.255.0 net_gateway" \
        "route 185.246.72.0 255.255.252.0 net_gateway" \
        "route 93.171.220.0 255.255.252.0 net_gateway" \
        "route 216.250.8.0 255.255.248.0 net_gateway" \
        "route 185.69.184.0 255.255.255.0 net_gateway" \
        "route 177.93.143.0 255.255.255.0 net_gateway" \
        "route 119.235.112.0 255.255.240.0 net_gateway" \
        "route 103.220.0.0 255.255.252.0 net_gateway"
    do
        grep -q "$route" "$CONFIG_FILE" || echo "$route" >> "$CONFIG_FILE"
    done

    echo "Konfigurasiýa täzelendi."

            # Network interfeysi restart
            #/etc/init.d/network start
            #echo "Network interfeysi tazelenyar..."
            
            # OpenVPN-ýi täzeden başlatmak
           # /etc/init.d/openvpn restart
           # /etc/init.d/openvpn start
            # /etc/init.d/openvpn start
            # /etc/init.d/openvpnc start
            # /etc/init.d/openvpn enable
            # /etc/init.d/openvpnc enable

            echo "OpenVPN täzeden başlatyldy."

           # ifup lan
        else
            echo "IP üýtgemedi, hiç zat edilmeýär."
        fi
    else
        echo "Täze IP alyp bolmady!"
        exit 1
    fi
fi

echo "Script tamamlandy."
